 
version: '3.1'

services:
    sfu:
        container_name: sfu
        image: ghcr.io/torkashvand630/mediasoup:v1
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 4443:4443/tcp 
            - 2700-3000:2700-3000/udp
            - 2700-3000:2700-3000/tcp
        environment:
            - DEBUG="mediasoup:INFO* *WARN* *ERROR*" 
            - INTERACTIVE="false" 
            - DOMAIN=localhost
            - PROTOO_LISTEN_PORT=4443  
            #- HTTPS_CERT_FULLCHAIN=/service/certs/live/sfu5.salampnu.ir/fullchain.pem 
            #- HTTPS_CERT_PRIVKEY=/service/certs/live/sfu5.salampnu.ir/privkey.pem 
            - MEDIASOUP_LISTEN_IP=0.0.0.0
            - MEDIASOUP_ANNOUNCED_IP=${myIP} 
            - MEDIASOUP_MIN_PORT=2700
            - MEDIASOUP_MAX_PORT=3000 
            - MEDIASOUP_USE_VALGRIND=false 
            - MEDIASOUP_VALGRIND_OPTIONS="--leak-check=full --track-fds=yes --log-file=/storage/mediasoup_valgrind_%p.log"  
            - MEDIASOUP_WORKER_BIN  
        volumes:            
            #- ${PWD}:/storage              
            - ${dataPath}sfu/server.js:/service/server.js    
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - cms  

    traefik:
        container_name: traefik
        image: ghcr.io/torkashvand630/traefik:1
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 80:80
            - 443:443
            - 8080:8080                          
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${dataPath}traefik/:/etc/traefik/
        #command: chown 600 /etc/traefik/acme.json
        #command: ["sh", "-c", "chmod -Rv 600 /etc/traefik/*"]   
        depends_on:
            - cms            

    mqtt:
        container_name: mqtt
        image: ghcr.io/torkashvand630/emqx:4.2.11
        restart: always
        networks:
            - meetnet
        ports:
            - 1883:1883
            - 8081:8081  
            - 8083:8083
            - 8084:8084  
            - 8883:8883
            - 18083:18083  
        volumes:                
            - ${dataPath}mqtt/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf
            - ${dataPath}mqtt/loaded_plugins:/opt/emqx/data/loaded_plugins
        depends_on:
            - cms              
          

    libre:
        container_name: libre
        image: ghcr.io/torkashvand630/collaboracode:6.4.0.6
        restart: always
        networks:
            - meetnet        
        ulimits:
          core: -1
        ports:
            - 9980:9980          
        environment:
            - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:net.frame_ancestors=${myDomian}
            - username=ali
            - password=pass11
            - domain=${myDomian}
        depends_on:
            - cms  

    cms:
        container_name: cms
        image: ghcr.io/torkashvand630/cms:v4
        restart: on-failure
        networks:
            - meetnet       
        volumes:
            - ${dataPath}/cms/cms:/var/www/html:cached
            - ${dataPath}/cms/dbdata:/var/www/dbdata      
            
    mysql:
        container_name: mysql
        image: ghcr.io/torkashvand630/mariadb:latest
        restart: on-failure
        networks:
            - meetnet
        #ports:
        #    - 3306:3306    
        environment:
            - MARIADB_ROOT_PASSWORD=pppp         
        volumes:
            - ${dataPath}/cms/dbdata:/var/lib/mysql
        depends_on:
            - cms
            - libre   
            - sfu
            - proom
            - monaco   

    proom:
        container_name: proom
        image: ghcr.io/torkashvand630/proom:b178
        restart: on-failure
        networks:
            - meetnet
        #ports:
        #    - 4001:5000    
        environment:
            - myDomian=${myDomian}
            - lang=${lang}
            - secret=$secret
        volumes:
            - ${dataPath}:/root/linux12/wwwroot/files/
        depends_on:
            - cms            


    monaco:
        container_name: monaco
        image: ghcr.io/torkashvand630/monaco:v2
        restart: always
        networks:
            - meetnet
        #ports:
        #    - 8181:8081
        depends_on:
            - cms            
                                 

networks:
  meetnet: {}        
