 
version: '3.1'

services:
    sfu:
        container_name: sfu
        image: alit771/mediasoup-demo:v1
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 4443:4443/tcp 
            - 2000-3000:2000-3000/udp
            - 2000-3000:2000-3000/tcp
        environment:
            - DEBUG="mediasoup:INFO* *WARN* *ERROR*" 
            - INTERACTIVE="false" 
            - DOMAIN=localhost
            - PROTOO_LISTEN_PORT=4443  
            - HTTPS_CERT_FULLCHAIN=/service/certs/live/sfu5.salampnu.ir/fullchain.pem 
            - HTTPS_CERT_PRIVKEY=/service/certs/live/sfu5.salampnu.ir/privkey.pem 
            - MEDIASOUP_LISTEN_IP=0.0.0.0
            - MEDIASOUP_ANNOUNCED_IP=${myIP} 
            - MEDIASOUP_MIN_PORT=2000
            - MEDIASOUP_MAX_PORT=3000 
            - MEDIASOUP_USE_VALGRIND=false 
            - MEDIASOUP_VALGRIND_OPTIONS="--leak-check=full --track-fds=yes --log-file=/storage/mediasoup_valgrind_%p.log"  
            - MEDIASOUP_WORKER_BIN  
        volumes:            
            - ${PWD}:/storage              
            - ${dataPath}sfu/server.js:/service/server.js    
            - /var/run/docker.sock:/var/run/docker.sock
    traefik:
        container_name: traefik
        image:  traefik:v2.3
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 80:80
            - 443:443
            - 8080:8080                          
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${dataPath}traefik/:/etc/traefik/
             
        depends_on:
            - proom            

    mqtt:
        container_name: mqtt
        image: emqx/emqx:4.2.11
        restart: always
        networks:
            - meetnet
        ports:
            - 1883:1883
            - 8081:8081  
            - 8083:8083
            - 8084:8084  
            - 8883:8883
            - 18083:18083  
        volumes:                
            - ${dataPath}mqtt/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf
            - ${dataPath}mqtt/loaded_plugins:/opt/emqx/data/loaded_plugins   
          

    libre:
        container_name: libre
        image: collabora/code:6.4.0.6
        restart: always
        networks:
            - meetnet        
        ulimits:
          core: -1
        ports:
            - 9980:9980          
        environment:
            - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:net.frame_ancestors=${myDomian}
            - username=ali
            - password=pass11
            - domain=${myDomian}                                  

    proom:
        container_name: proom
        image: alit771/proom:b165
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 4001:5000    
        environment:
            - myDomian=${myDomian}
            - lang=${lang}
            - secret=$secret
        volumes:
            - ${dataPath}:/root/linux12/wwwroot/files/

    monaco:
        container_name: monaco
        image: alit771/monaco:v2
        restart: always
        networks:
            - meetnet
        ports:
            - 8181:8081
                                 

networks:
  meetnet: {}
         