 
version: '3.1'

services:

    traefik:
        container_name: traefik
        image:  traefik:v2.3
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 80:80
            - 443:443
            - 8080:8080                          
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${dataPath}traefik/:/etc/traefik/
             
        depends_on:
            - proom            

    mqtt:
        container_name: mqtt
        image: emqx/emqx:4.2.11
        restart: always
        networks:
            - meetnet
        ports:
            - 1883:1883
            - 8081:8081  
            - 8083:8083
            - 8084:8084  
            - 8883:8883
            - 18083:18083       
          

    libre:
        container_name: libre
        image: collabora/code:6.4.0.6
        restart: always
        networks:
            - meetnet        
        ulimits:
          core: -1
        ports:
            - 9980:9980          
        environment:
            - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:net.frame_ancestors=${myDomian}
            - username=ali
            - password=pass11
            - domain=${myDomian}
        
    sfu:
        container_name: sfu
        image: alit771/sfu:v6
        restart: always
        networks:
            - meetnet
        ports:
            - 7000:7000
            - "5000-5200:5000-5200/udp"                             

    proom:
        container_name: proom
        image: alit771/proom:b135
        restart: on-failure
        networks:
            - meetnet
        ports:
            - 4001:5000    
        environment:
            - myDomian=${myDomian}
            - lang=${lang}
            - secret=$secret
        volumes:
            - ${dataPath}:/root/linux12/wwwroot/files/

networks:
  meetnet: {}
         