http:   
  routers:

    proom:     
      rule: "Host(`myDomian`)"
      tls:
        certResolver: myresolver      
      service: 'proom'  

    mqtt:     
      rule: "Host(`myDomian`) && Path(`/mqtt`)"
      tls:
        certResolver: myresolver          
      service: 'mqtt'

    libre:     
      rule: "Host(`myDomian`) && (PathPrefix(`/lool/`) || PathPrefix(`/loleaflet/`) || PathPrefix(`/hosting/`))"
      tls:
        certResolver: myresolver      
      service: 'libre'
     
    sfu:     
      rule: "Host(`myDomian`) && Path(`/ws`)"
      tls:
        certResolver: myresolver           
      service: 'sfu'

    monaco:     
      rule: "Host(`myDomian`) && PathPrefix(`/mmonaco`)"
      tls:
        certResolver: myresolver           
      service: 'monaco'


  services:
    proom:
      loadBalancer:        
        servers:         
          - url: http://proom:5000

    mqtt:
      loadBalancer:        
        servers:          
          - url: http://mqtt:8083          
            
    libre:
      loadBalancer:        
        servers:          
          - url: http://libre:9980
             
    sfu:
      loadBalancer:        
        servers:         
          - url: http://sfu:7000

    monaco:
      loadBalancer:        
        servers:          
          - url: http://monaco:8081   
           
                   