http:
  middlewares:
    add-foo:
      addPrefix:
        prefix: "/psd"
    example:
      stripPrefix:
        prefixes:
          - "/psd"
        forceSlash: false

  routers:

    proom2:     
      rule: "Host(`myDomian`) && (PathPrefix(`/wopi/`) || PathPrefix(`/monaco`) || PathPrefix(`/webapp/`) || PathPrefix(`/VisualMathEditor/`))"
      tls:
        certResolver: myresolver      
      service: 'proom'  
      middlewares:
        - "add-foo"     

    cms:     
      rule: "Host(`myDomian`)"
      tls:
        certResolver: myresolver      
      service: 'cms'  

    proom:     
      rule: "Host(`myDomian`) && (PathPrefix(`/psd/`))"
      tls:
        certResolver: myresolver      
      service: 'proom'  

    mqtt:     
      rule: "Host(`myDomian`) && Path(`/mqtt`)"
      tls:
        certResolver: myresolver          
      service: 'mqtt'

    libre:     
      rule: "Host(`myDomian`) && (PathPrefix(`/lool/`) || PathPrefix(`/loleaflet/`) || PathPrefix(`/hosting/`))"
      tls:
        certResolver: myresolver      
      service: 'libre'
     
    sfu:     
      rule: "Host(`myDomian`) && PathPrefix(`/sfu/`)"
      tls:
        certResolver: myresolver           
      service: 'sfu'

    monaco:     
      rule: "Host(`myDomian`) && PathPrefix(`/mmonaco`)"
      tls:
        certResolver: myresolver           
      service: 'monaco'


  services:
    proom:
      loadBalancer:        
        servers:         
          - url: http://proom:5000

    cms:
      loadBalancer:        
        servers:         
          - url: http://cms:80

    mqtt:
      loadBalancer:        
        servers:          
          - url: http://mqtt:8083          
            
    libre:
      loadBalancer:        
        servers:          
          - url: http://libre:9980
             
    sfu:
      loadBalancer:        
        servers:         
          - url: http://sfu:4443

    monaco:
      loadBalancer:        
        servers:          
          - url: http://monaco:8081   
           
                   