
api:
  dashboard: true
  insecure: true

entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
      
  
    websecure:
      address: ":443"

    other:
      address: ":447"    
      
    udpep:
      address: ":446/udp"  
           
  
certificatesResolvers:
    myresolver:
      acme:
        email: abolfati@gmail.com
        storage: /etc/traefik/acme.json
        httpChallenge:          
          entryPoint: web  
       
    
providers:  
  file:
    filename: "/etc/traefik/all.yml"
    watch: true          
